apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: paw-suite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: admin-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"

            - name: MONGODB_DATABASE_URI
              value: "mongodb://admin:password@mongo:27017/brand_threat?authSource=admin"

            - name: MONGODB_DATABASE_NAME
              value: "brand_threat"
